Class {
	#name : 'IdleMutator',
	#superclass : 'Mutator',
	#category : 'Ranger-Exploring',
	#package : 'Ranger-Exploring'
}

{ #category : 'as yet unclassified' }
IdleMutator >> mutateAddConstraint: aConstraint [

	^ aConstraint
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateAndConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateBitAddConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateBitOrConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateBitShiftConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateDivisionConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateEqualsConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateGreaterConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateGreaterOrEqualsConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateIsBooleanObjectOfConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateIsCharacterObjectConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateIsClassIndexOfConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateIsContextObjectConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateIsFloatObjectOfConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateIsIntegerObjectConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateIsIntegerObjectOfConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateIsIntegerToFloatConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateIsNonCharacterConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateIsNonIntegerConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateLessConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateLessOrEqualsConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateModuloConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateMultiplicationConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateNotEqualsConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateOrConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateQuotientConstraint: aConstraint [

	^ aConstraint 
]

{ #category : 'as yet unclassified' }
IdleMutator >> mutateSubstractionConstraint: aConstraint [

	^ aConstraint 
]
