Class {
	#name : 'RASlot',
	#superclass : 'Object',
	#instVars : [
		'index',
		'value'
	],
	#category : 'Ranger-Exploring',
	#package : 'Ranger-Exploring'
}

{ #category : 'accessing' }
RASlot >> index [

	^ index
]

{ #category : 'accessing' }
RASlot >> index: anObject [

	index := anObject
]

{ #category : 'evaluating' }
RASlot >> value [

	^ value
]

{ #category : 'accessing' }
RASlot >> value: anObject [

	value := anObject
]
