Class {
	#name : 'RASyntacticArrayPathMutator',
	#superclass : 'RASyntacticPathMutator',
	#category : 'Ranger-Exploring',
	#package : 'Ranger-Exploring'
}

{ #category : 'as yet unclassified' }
RASyntacticArrayPathMutator >> constraintsVariationsFrom: pathConstraints [
	"Returns a set of pathConsraints ( which is an array )"
	"TODO: Implement me"
	^ {}
]

{ #category : 'as yet unclassified' }
RASyntacticArrayPathMutator >> isMutable: aPath [
	"TODO: Implement me please"
	^ false
]
