Class {
	#name : 'RASyntacticArrayPathMutatorTest',
	#superclass : 'RASyntacticPathMutatorTest',
	#category : 'Ranger-Exploring',
	#package : 'Ranger-Exploring'
}

{ #category : 'tests' }
RASyntacticArrayPathMutatorTest >> testWhenIsAPathArray [
	"TODO: Implement me please"
	self assert: false equals: true
]

{ #category : 'tests' }
RASyntacticArrayPathMutatorTest >> testWhenIsNotAPathArray [
	"TODO: Implement me please"
	self assert: false equals: true
]
